services:
  frontend:
    build: client
    ports:
      - 5000:80
    environment:
      - VITE_backend_url=https://psychic-meme-wq7qj557wp4hv6wv-8080.app.github.dev/
  backend:
    build: server
    ports:
      - 8080:8000